In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import ClusterCentroids

# Read the CSV

In [3]:
# Load the data
df = pd.read_csv('encoded_loans_dfV2.0.csv', index_col='LoanNumber')

# Split the Data into Training and Testing

In [4]:
# Create our features
X = df.drop(columns='LoanStatus', axis=1)

# Create our target
y = df['LoanStatus']

In [5]:
X.describe()

BorrowerZip         Term  InitialApprovalAmount  \
count   1207.000000  1207.000000           1.207000e+03   
mean   80215.137531    38.913007           1.361594e+05   
std       19.105867    17.740666           4.136190e+05   
min    80012.000000    24.000000           5.000000e+02   
25%    80205.000000    24.000000           1.856450e+04   
50%    80211.000000    24.000000           4.290000e+04   
75%    80222.000000    60.000000           1.061915e+05   
max    80401.000000    60.000000           7.275742e+06   

       CurrentApprovalAmount  JobsReported  ForgivenessAmount       rating  \
count           1.207000e+03   1207.000000       1.207000e+03  1207.000000   
mean            1.359278e+05     14.321458       1.347085e+05     4.143331   
std             4.135207e+05     37.148812       4.088977e+05     1.068043   
min             5.000000e+02      1.000000       5.046500e+02     1.000000   
25%             1.830850e+04      2.000000       1.810364e+04     4.000000   
50%             4.300000e+04      5.000000       4.290235e+04     4.500000   
75%             1.061415e+05     12.000000       1.064222e+05     5.000000   
max             7.275742e+06    500.000000       7.356988e+06     5.000000   

       review_count          lat          lon  ...  MonthApproved_1  \
count   1207.000000  1207.000000  1207.000000  ...      1207.000000   
mean      69.122618    39.722251  -104.966978  ...         0.093621   
std      172.585119     0.047072     0.052903  ...         0.291421   
min        1.000000    39.368946  -105.245930  ...         0.000000   
25%        3.000000    39.692745  -104.994540  ...         0.000000   
50%        8.000000    39.728643  -104.976669  ...         0.000000   
75%       44.000000    39.751481  -104.937029  ...         0.000000   
max     1661.000000    40.036910  -104.670690  ...         1.000000   

       MonthApproved_2  MonthApproved_3  MonthApproved_4  MonthApproved_5  \
count      1207.000000      1207.000000      1207.000000      1207.000000   
mean          0.155758         0.065452         0.447390         0.201326   
std           0.362776         0.247423         0.497431         0.401157   
min           0.000000         0.000000         0.000000         0.000000   
25%           0.000000         0.000000         0.000000         0.000000   
50%           0.000000         0.000000         0.000000         0.000000   
75%           0.000000         0.000000         1.000000         0.000000   
max           1.000000         1.000000         1.000000         1.000000   

       MonthApproved_6  MonthApproved_7  MonthApproved_8  YearApproved_2020  \
count      1207.000000      1207.000000      1207.000000        1207.000000   
mean          0.017399         0.012428         0.006628           0.649544   
std           0.130805         0.110830         0.081176           0.477310   
min           0.000000         0.000000         0.000000           0.000000   
25%           0.000000         0.000000         0.000000           0.000000   
50%           0.000000         0.000000         0.000000           1.000000   
75%           0.000000         0.000000         0.000000           1.000000   
max           1.000000         1.000000         1.000000           1.000000   

       YearApproved_2021  
count        1207.000000  
mean            0.350456  
std             0.477310  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             1.000000  
max             1.000000  

[8 rows x 45 columns]

In [6]:
# Check the balance of our target values
df['LoanStatus'].value_counts()

Paid in Full    1174
Exemption 4       33
Name: LoanStatus, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [8]:
# Resample the training data with the RandomOversampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'Paid in Full': 881, 'Exemption 4': 881})

In [9]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [10]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.736253318164581

In [11]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  8,   1],
       [122, 171]], dtype=int64)

In [12]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                    pre       rec       spe        f1       geo       iba       sup

 Exemption 4       0.06      0.89      0.58      0.12      0.72      0.53         9
Paid in Full       0.99      0.58      0.89      0.74      0.72      0.50       293

 avg / total       0.97      0.59      0.88      0.72      0.72      0.50       302



### SMOTE Oversampling

In [13]:
# Resample the training data with SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy='auto').fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'Paid in Full': 881, 'Exemption 4': 881})

In [14]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [15]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7396662874478575

In [16]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  8,   1],
       [120, 173]], dtype=int64)

In [17]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                    pre       rec       spe        f1       geo       iba       sup

 Exemption 4       0.06      0.89      0.59      0.12      0.72      0.54         9
Paid in Full       0.99      0.59      0.89      0.74      0.72      0.51       293

 avg / total       0.97      0.60      0.88      0.72      0.72      0.51       302



# Undersampling

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [18]:
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'Exemption 4': 24, 'Paid in Full': 24})

In [19]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [20]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.434963974213121

In [21]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  7,   2],
       [266,  27]], dtype=int64)

In [22]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                    pre       rec       spe        f1       geo       iba       sup

 Exemption 4       0.03      0.78      0.09      0.05      0.27      0.08         9
Paid in Full       0.93      0.09      0.78      0.17      0.27      0.07       293

 avg / total       0.90      0.11      0.76      0.16      0.27      0.07       302

